# Generated by Django 5.2.12 on 2026-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicios', 'Servicios'), ('sueldos', 'Sueldos'), ('software', 'Software'), ('marketing', 'Marketing'), ('otros', 'Otros')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
